### ISSUE TITLE
2019 June - September Milestone Plan

### ISSUE THREAD

**Issue by omolazabal** [flow-thru/flowthru#10]
## Description
This milestone captures the initial configurations of the web application to prepare for ACM Project Jam.

## Time Frame
2019 June 20th - August 24th

## Context
- [Fall 2019 Roadmap](https://github.com/flow-thru/flowthru/wiki/Roadmap#fall-2019-roadmap)

#### GitHub
- [x] Complete the initial state of the wiki pages #34
- [x] Complete the markdown files to assist contributors #35

#### DevOps
- [x] Create an Elastic Beanstalk (EB) web application & host client DockerFiles #28
- [x] Create DockerFiles for development and deployment #33
- [x] Create Travis CI/CD testing and deployment pipelines #37

#### Server
- [x] Design the initial state of the database #39 
- [x] Create a simple REST API to access Users #38
