### ISSUE TITLE
2019 September - October Milestone Plan

### ISSUE THREAD

**Issue by omolazabal** [flow-thru/flowthru#70]
## Description
This milestone captures initial API and UI/UX implementations for user authentication and user navigation. The application will not be production ready by the end of the milestone

## Time Frame
2019 September 23rd - October 25th

## Context
[Fall 2019 Roadmap](https://github.com/flow-thru/flowthru/wiki/Fall-2019-Roadmap)

## Tasks
List the enhancements that are to be worked on during this milestone.

#### API
- [ ] Set up Auth0 for application #71 
- [ ] Create endpoints to obtain a user's information for the profile page #73 

#### UI/UX
- [ ] Create a landing page where unregistered users can login or create a profile #75 
- [ ] Create a profile drop down menu on the top bar. It features the ability to view your profile page and create an organization #80 
- [ ] Create a basic profile page where users can view information about themselves #78
